# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inspect.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rinspect.proto\"\xa1\x01\n\tOsRelease\x12\x15\n\rcli_formatted\x18\x01 \x01(\t\x12\x0e\n\x06\x64istro\x18\x02 \x01(\t\x12\x15\n\rmajor_version\x18\x03 \x01(\t\x12\x15\n\rminor_version\x18\x04 \x01(\t\x12#\n\x0c\x61rchitecture\x18\x05 \x01(\x0e\x32\r.Architecture\x12\x1a\n\tdistro_id\x18\x06 \x01(\x0e\x32\x07.Distro\"\x9e\x03\n\x11InspectionResults\x12\x1e\n\nos_release\x18\x01 \x01(\x0b\x32\n.OsRelease\x12\x15\n\rbios_bootable\x18\x02 \x01(\x08\x12\x15\n\ruefi_bootable\x18\x03 \x01(\x08\x12\x0f\n\x07root_fs\x18\x04 \x01(\t\x12\x30\n\nerror_when\x18\x05 \x01(\x0e\x32\x1c.InspectionResults.ErrorWhen\x12\x17\n\x0f\x65lapsed_time_ms\x18\x06 \x01(\x03\x12\x10\n\x08os_count\x18\x07 \x01(\x05\"\xcc\x01\n\tErrorWhen\x12\x0c\n\x08NO_ERROR\x10\x00\x12\x13\n\x0fSTARTING_WORKER\x10\x64\x12\x12\n\x0eRUNNING_WORKER\x10\x65\x12\x13\n\x0eMOUNTING_GUEST\x10\xc8\x01\x12\x12\n\rINSPECTING_OS\x10\xc9\x01\x12\x1a\n\x15INSPECTING_BOOTLOADER\x10\xca\x01\x12\x1d\n\x18\x44\x45\x43ODING_WORKER_RESPONSE\x10\xac\x02\x12$\n\x1fINTERPRETING_INSPECTION_RESULTS\x10\xad\x02*\xee\x01\n\x06\x44istro\x12\x12\n\x0e\x44ISTRO_UNKNOWN\x10\x00\x12\x0c\n\x07WINDOWS\x10\xe8\x07\x12\x0b\n\x06\x44\x45\x42IAN\x10\xd0\x0f\x12\x0b\n\x06UBUNTU\x10\xd1\x0f\x12\t\n\x04KALI\x10\xd2\x0f\x12\r\n\x08OPENSUSE\x10\xb8\x17\x12\t\n\x04SLES\x10\xb9\x17\x12\r\n\x08SLES_SAP\x10\xba\x17\x12\x0b\n\x06\x46\x45\x44ORA\x10\xa0\x1f\x12\t\n\x04RHEL\x10\xa1\x1f\x12\x0b\n\x06\x43\x45NTOS\x10\xa2\x1f\x12\x0b\n\x06\x41MAZON\x10\xa3\x1f\x12\x0b\n\x06ORACLE\x10\xa4\x1f\x12\n\n\x05ROCKY\x10\xa5\x1f\x12\x12\n\rCENTOS_STREAM\x10\xa6\x1f\x12\t\n\x04\x41RCH\x10\x88\'\x12\n\n\x05\x43LEAR\x10\xf0.*:\n\x0c\x41rchitecture\x12\x18\n\x14\x41RCHITECTURE_UNKNOWN\x10\x00\x12\x07\n\x03X86\x10\x01\x12\x07\n\x03X64\x10\x02\x42\x06Z\x04.;pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inspect_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004.;pb'
  _DISTRO._serialized_start=599
  _DISTRO._serialized_end=837
  _ARCHITECTURE._serialized_start=839
  _ARCHITECTURE._serialized_end=897
  _OSRELEASE._serialized_start=18
  _OSRELEASE._serialized_end=179
  _INSPECTIONRESULTS._serialized_start=182
  _INSPECTIONRESULTS._serialized_end=596
  _INSPECTIONRESULTS_ERRORWHEN._serialized_start=392
  _INSPECTIONRESULTS_ERRORWHEN._serialized_end=596
# @@protoc_insertion_point(module_scope)
# Don't run flake8 on gnerated Python files.
# flake8: noqa
