"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
 Copyright 2020 Google Inc. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import inspect_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class OutputInfo(google.protobuf.message.Message):
    """OutputInfo records output info from the tools."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SOURCES_SIZE_GB_FIELD_NUMBER: builtins.int
    TARGETS_SIZE_GB_FIELD_NUMBER: builtins.int
    FAILURE_MESSAGE_FIELD_NUMBER: builtins.int
    FAILURE_MESSAGE_WITHOUT_PRIVACY_INFO_FIELD_NUMBER: builtins.int
    SERIAL_OUTPUTS_FIELD_NUMBER: builtins.int
    IMPORT_FILE_FORMAT_FIELD_NUMBER: builtins.int
    DETECTED_SOURCES_SIZE_GB_FIELD_NUMBER: builtins.int
    INFLATION_TYPE_FIELD_NUMBER: builtins.int
    INFLATION_TIME_MS_FIELD_NUMBER: builtins.int
    SHADOW_INFLATION_TIME_MS_FIELD_NUMBER: builtins.int
    SHADOW_DISK_MATCH_RESULT_FIELD_NUMBER: builtins.int
    IS_UEFI_COMPATIBLE_IMAGE_FIELD_NUMBER: builtins.int
    IS_UEFI_DETECTED_FIELD_NUMBER: builtins.int
    INSPECTION_RESULTS_FIELD_NUMBER: builtins.int
    INFLATION_FALLBACK_REASON_FIELD_NUMBER: builtins.int
    @property
    def sources_size_gb(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """Size of import/export sources (image/disk/file)"""
    @property
    def targets_size_gb(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """Size of import/export targets (image/disk/file)"""
    failure_message: builtins.str
    """Failure message of the command"""
    failure_message_without_privacy_info: builtins.str
    """Failure message of the command without privacy info"""
    @property
    def serial_outputs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Each element is the serial output log of a worker instance.
        This is only populated if the workflow fails.
        """
    import_file_format: builtins.str
    """Import file format"""
    @property
    def detected_sources_size_gb(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """Size of import/export sources (image/disk/file) that was detected.
        sources_size_gb, in contrast, contains the actual value. Ideally
        these values will match; a mismatch indicates an error in our
        detection.
        """
    inflation_type: builtins.str
    """Inflation type, which can be qemu or API."""
    @property
    def inflation_time_ms(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """Inflation time"""
    @property
    def shadow_inflation_time_ms(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """Inflation time of the shadow disk.  It's for new API validation."""
    shadow_disk_match_result: builtins.str
    """Shadow disk match result for shadow disk inflater. It's for new API
    validation.
    """
    is_uefi_compatible_image: builtins.bool
    """Indicates whether the image is imported and marked as UEFI_COMPATIBLE."""
    is_uefi_detected: builtins.bool
    """Indicates whether the image is auto-detected to be UEFI compatible."""
    @property
    def inspection_results(self) -> inspect_pb2.InspectionResults:
        """Inspection results. Ref to the def of 'InspectionResults' to see details."""
    inflation_fallback_reason: builtins.str
    """Inflation fallback reason"""
    def __init__(
        self,
        *,
        sources_size_gb: collections.abc.Iterable[builtins.int] | None = ...,
        targets_size_gb: collections.abc.Iterable[builtins.int] | None = ...,
        failure_message: builtins.str = ...,
        failure_message_without_privacy_info: builtins.str = ...,
        serial_outputs: collections.abc.Iterable[builtins.str] | None = ...,
        import_file_format: builtins.str = ...,
        detected_sources_size_gb: collections.abc.Iterable[builtins.int] | None = ...,
        inflation_type: builtins.str = ...,
        inflation_time_ms: collections.abc.Iterable[builtins.int] | None = ...,
        shadow_inflation_time_ms: collections.abc.Iterable[builtins.int] | None = ...,
        shadow_disk_match_result: builtins.str = ...,
        is_uefi_compatible_image: builtins.bool = ...,
        is_uefi_detected: builtins.bool = ...,
        inspection_results: inspect_pb2.InspectionResults | None = ...,
        inflation_fallback_reason: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["inspection_results", b"inspection_results"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["detected_sources_size_gb", b"detected_sources_size_gb", "failure_message", b"failure_message", "failure_message_without_privacy_info", b"failure_message_without_privacy_info", "import_file_format", b"import_file_format", "inflation_fallback_reason", b"inflation_fallback_reason", "inflation_time_ms", b"inflation_time_ms", "inflation_type", b"inflation_type", "inspection_results", b"inspection_results", "is_uefi_compatible_image", b"is_uefi_compatible_image", "is_uefi_detected", b"is_uefi_detected", "serial_outputs", b"serial_outputs", "shadow_disk_match_result", b"shadow_disk_match_result", "shadow_inflation_time_ms", b"shadow_inflation_time_ms", "sources_size_gb", b"sources_size_gb", "targets_size_gb", b"targets_size_gb"]) -> None: ...

global___OutputInfo = OutputInfo
