# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: output_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import inspect_pb2 as inspect__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11output_info.proto\x1a\rinspect.proto\"\xe1\x03\n\nOutputInfo\x12\x17\n\x0fsources_size_gb\x18\x01 \x03(\x03\x12\x17\n\x0ftargets_size_gb\x18\x02 \x03(\x03\x12\x17\n\x0f\x66\x61ilure_message\x18\x03 \x01(\t\x12,\n$failure_message_without_privacy_info\x18\x04 \x01(\t\x12\x16\n\x0eserial_outputs\x18\x05 \x03(\t\x12\x1a\n\x12import_file_format\x18\x06 \x01(\t\x12 \n\x18\x64\x65tected_sources_size_gb\x18\x07 \x03(\x03\x12\x16\n\x0einflation_type\x18\x08 \x01(\t\x12\x19\n\x11inflation_time_ms\x18\t \x03(\x03\x12 \n\x18shadow_inflation_time_ms\x18\n \x03(\x03\x12 \n\x18shadow_disk_match_result\x18\x0b \x01(\t\x12 \n\x18is_uefi_compatible_image\x18\x0c \x01(\x08\x12\x18\n\x10is_uefi_detected\x18\r \x01(\x08\x12.\n\x12inspection_results\x18\x0e \x01(\x0b\x32\x12.InspectionResults\x12!\n\x19inflation_fallback_reason\x18\x0f \x01(\tB\x06Z\x04.;pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'output_info_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004.;pb'
  _OUTPUTINFO._serialized_start=37
  _OUTPUTINFO._serialized_end=518
# @@protoc_insertion_point(module_scope)
# Don't run flake8 on gnerated Python files.
# flake8: noqa
